fix "please adopt containerbackground api" in widget after ios 17.0;
AnderGoig/github-contributions-ios pull request #22
Opened 2024-03-02 03:48 UTC by ynrng

widget shows an error on initialisation after upgrading to iOS 17. This fix is based on https://stackoverflow.com/a/76842922/8262079. Tested on iOS 17.3.1 on iPhone.

2024-03-03 13:24 UTC, AnderGoig requested changes
thanks @ynrng, nice contribution!

can we a few code style changes? 🙏

2024-03-03 13:24 UTC, AnderGoig commented on GitHubContributionsWidget/GitHubContributionsGraphEntryView.swift
> +
```suggestion
```

2024-03-03 13:24 UTC, AnderGoig commented on GitHubContributionsWidget/GitHubContributionsGraphEntryView.swift
> +
```suggestion

```

2024-03-04 00:09 UTC, ynrng commented
committed.

2024-03-04 12:42 UTC, merged